### ISSUE TITLE
switch `delThumbs()` to `october:util purge thumbs --force`

### ISSUE THREAD

**Issue by matteotrubini** [romanov-acc/octobercms_clearcachewidget#14]
https://github.com/romanov-acc/octobercms_clearcachewidget/blob/9956e0ad503fd5207938363e92eb47962b7ef120/reportwidgets/ClearCache.php#L67-L69

`delThumbs()` can be substituted by

`Artisan::call('october:util', ['name' => 'purge thumbs', '--force' => true]);`

making itself, `thumbspath` and `thumb_regex` properties surpassed.

**Comment by alserom** [comment]
Hi @matteotrubini.
Can you describe why proposed solution better than current?
Also, I do not clearly understand what you mean when say 
> making itself, thumbspath and thumb_regex properties surpassed.

 My English not so good, so can you explain in other words please what you mean?

**Comment by matteotrubini** [comment]
I'll make a PR in few hours :+1:
