### ISSUE TITLE
Thumbnails with no crop parameter

### ISSUE THREAD

**Issue by Denoder** [romanov-acc/octobercms_clearcachewidget#8]
does the plugin also check for thumbs with the no crop parameter? Cause i usually dont put it in and images will have these in it:

"/storage/app/uploads/public/569/c69/26a/thumb_8_300x450_0_0_auto.jpg"

**Comment by alserom** [comment]
Hi @Teranode! Thank you for issue.
I added the option `Regex for thumb file names`, so you can set the pattern by which to delete files.
For example, you can use `/^thumb_.*/` pattern. Update plugin to 1.2.0 version and try it.
